"""empty message

Revision ID: 38fa470be2ad
Revises: 
Create Date: 2019-12-23 21:01:38.361418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fa470be2ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluestack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('passw', sa.String(length=255), nullable=True),
    sa.Column('defin', sa.String(length=255), nullable=True),
    sa.Column('stack_i', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clue_txt', sa.String(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['cluestack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clue')
    op.drop_table('user')
    op.drop_table('cluestack')
    # ### end Alembic commands ###
